### PR TITLE
Create order-of-linking.md

### PR DESCRIPTION
**Pull request by enhide**
I have created a huge diagram describing various build targets in the CJDNS project, and the list of files linked to achieve these targets.

### CODE REVIEW

**Comment by willeponken** [comment]
@enhide I think @thefinn93 want the link:

`[CJDNS Build Targets And Order Of Linking](https://raw.githubusercontent.com/ProjectMeshnet/documentation/master/en/cjdns/order-of-linking.png)`

changed to:

`[CJDNS Build Targets And Order Of Linking](/en/cjdns/order-of-linking.png)`

or am I wrong?

**Comment by cschmittiey** [comment]
@willeponken @enhide Yeah, that's definitely the right way to do it. Links should be relative, not absolute.

**Comment by lukevers** [comment]
It wouldn't be correct to have github content links when this repo is hosted in more than one place. Especially if someone downloaded the repo and didn't have access to github content locally.

**Comment by kpcyrd** [comment]
Done! Thanks for your contribution.

**Pull request merged**
